### ISSUE TITLE
obfuscate: "query not parsed" for a legitimate looking MySQL query

### ISSUE THREAD

**Issue by simonw** [DataDog/datadog-trace-agent#316]
We're getting the `agent.parse.error` of `Query not parsed` for the following SQL query, which I think the SQL parser should be able to handle:

    /* ADB: /sample-path correlation_id:08a3cb269f3211e793b90e80c6e864fc */
    select id,field1,field2,field3 from OTable where evnt = %s 
    and OTable.status = %s
    and ((OTable.survey = "direct" and OTable.payment in ("scramble", "eggs")) 
        or (OTable.email is not null and OTable.email != "")) 
    and OTable.status != 350 order by %s

(I added newlines to the above to make it more readable - the query in question does not have newlines in it)

**Comment by ufoot** [comment]
I stumbled on this while searching from another issue, just for the record, the problem here is likely the `""` in `OTable.email != ""`. AFAIK the parser considers whatever is enclosed in `"` is an identifier and not a string value so it's equivalent to `(OTable.email is not null and OTable.email != )` which... is not correct.

**Comment by gbbr** [comment]
I’ve made some changes recently around the behavior of double quoted strings, perhaps a more recent version would not return an error? I realise this issue is a year old now and I apologise for the lack of responses, but if you are still active and still have this problem, it would help if you could post the original (unmodified) query.

**Comment by gbbr** [comment]
Should be fixed now.
