### ISSUE TITLE
cannot decode v0.3 traces payload: read limit reached

### ISSUE THREAD

**Issue by ludwikbukowski** [DataDog/datadog-trace-agent#497]
I receive such an error:
```
[ TRACE ] 2018-10-17 22:00:12 ERROR (receiver.go:386) - cannot decode v0.3 traces payload: read limit reached
```
I guess its related to huge number of spans that are sent within the trace.
If so, where is this limit configurable? Whats the default value?

**Comment by gbbr** [comment]
This happens when the payload sent by the tracer is larger than the maximum accepted by the trace agent (currently 10M). Normally tracers should not do this, so I'd guess this is most likely a tracer problem. Which language are you using?

**Comment by ludwikbukowski** [comment]
Elixir

**Comment by gbbr** [comment]
I don't think we have official support for Elixir, so you are probably
using a custom implementation, am I right? In that case, you should ensure
that the payload you are sending is within the maximum limit.

**Comment by ludwikbukowski** [comment]
right, this library: 
https://github.com/spandex-project/spandex
Its quite good anyway

**Comment by gbbr** [comment]
Thanks. I will close the issue in that case, since there is nothing to do here. But feel free to post here if you have more questions about how to do this.

What we do in some of our tracers is that we start flushing once the payload size goes above 5MB. If you don't have the size handy you can simply use a different size heuristic. For example, OpenCensus does [this](https://github.com/census-instrumentation/opencensus-go/blob/6edeb78af2d9e4f169abb223feaef35da2e45d06/exporter/stackdriver/trace.go#L85-L88) to get an estimate of a size. You could do something similar if getting an approximation of the msgpack load is not possible with whatever library exists in Elixir.
